### ISSUE TITLE
Go directly into OFW

### ISSUE THREAD

**Issue by x43x61x69** [sthetix/HATS#10]
I know it's not directly related but asked here since you knew the hardware pretty well.

I've an OLED with modchip. After hwfly_toolbox firmware update failed, it only go directly into OFW so seems the chip no longer works. However, since I got the device from the installer, it only show static green light constantly even after successfully enter hekate or in sleep mode. Is the chip installed incorrectly/faulty since I got it? It still shown static green led even when it's not working.

Hope you can share some insight, thank you.

**Comment by sthetix** [comment]
Try to reset the chip, if it doesn't work, please try to reflash the chip
using a usb connection. By doing this we will know if the chip is faulty or
not.
