### ISSUE TITLE
error tidak keluar menu overlay jdi gak bisa cheat

### ISSUE THREAD

**Issue by putra1990** [sthetix/HATS#11]
emunand fw 15.0.0 chip hwfly

tidak keluar menu overlay
jdi gak bisa gunakan cheat edlizon

**Comment by sthetix** [comment]
Coba cek di  github tesla nya.

**Comment by putra1990** [comment]
closed

update edlizon jdi lancar makasi gan

**Comment by Smvxmen** [comment]
> closed
> 
> update edlizon jdi lancar makasi gan

Caranya gmn? Cm update doang? Py gue update tpi ga bisa
