### ISSUE TITLE
Connect to Nintendo Servers

### ISSUE THREAD

**Issue by EvanPokemon101** [sthetix/HATS#12]
Is there something in place in this pack that blocks connection to Nintendo Servers? And if so, how can I disable that?

**Comment by ZachieBlade** [comment]
Are you trying to get banned? This is how you get banned.

**Comment by sthetix** [comment]
You need to get to the ofw mode to connect to the Nintendo server.

On hekate, select reboot then ofw..

Please read the hats pack description
