### ISSUE TITLE
1.5.0 Pre-release init issues

### ISSUE THREAD

**Issue by Ozfer** [sthetix/HATS#15]
Latest 1.5.0 not bootable on my OLED switch I get an error cannot init SD card. Reverted to 1.4.1 and it works again.

**Comment by sthetix** [comment]
No issue here on my end. I use a Samsung SD Evo Plus SD card.

**Comment by Ozfer** [comment]
Using SanDisk Ultra 1TB I have downloaded 1.5.0 twice and extracted it to SD card three times with 7ZIP overwriting files. With 1.5.0 I consistently get error "Failed to init or mount SD!". When I flash it back extracting files the same way with 7ZIP it boots up without issues. This SD card has plenty of space and has never had an issue with previous releases.

**Comment by sthetix** [comment]
FYI, Sandisk 1TB has a compatibility issue with the chip.
That is why all of my modded consoles use Samsung Evo SD cards

**Comment by Ozfer** [comment]
https://github.com/CTCaer/hekate/issues/833 looks like a known Hekate 6.0.2 issue

**Comment by sthetix** [comment]
And as I said previously, Sandisk has issues with the chip. But let's wait
to get it sorted out
