### ISSUE TITLE
Version control is confusing 

### ISSUE THREAD

**Issue by dryja123** [sthetix/HATS#16]
Changes made to the pack is confusing to follow. For example, version 15.0.0 was uploaded a few days ago but the zip file was changed yesterday. I don’t know what changed or what’s different about it. 

It would be easier to understand what changed if the version changed to something like 15.0.1.

**Comment by sthetix** [comment]
There is no 15.0.x. I always update the pack because the components are
always updated (for example dbi is now version 506 instead of 504 in just
one or two days), and i just cannot re-number the  pack version again and
again as that would be very confusing for the user.

**Comment by sthetix** [comment]
Ok, I think I will re-number the version, but i will keep it in a single
post so you can keep track of every pack you have downloaded.

**Comment by dryja123** [comment]
I think that makes things clean and easy. There were a ton of updates to HATS pack 14.0.0. In my downloads folder I have multiple copies of 14.0.0 (1) (2) (3)… etc

ultimately, it your pack and you can do what you want. I’m thankful for it. I think it would be less confusing for people if they see something like 15.0.1 and they know that a component of the pack was changed and updated.

**Comment by sthetix** [comment]
I will do it for later release
Thanks for the suggestion
