### ISSUE TITLE
firmware 16.0 and firmware 16.01

### ISSUE THREAD

**Issue by putra1990** [sthetix/HATS#18]
gan baik fw 16 dan 16.01
dan hat terbaru

ada 2 masalah
pas mau masuk menu tesla atau edlizon ovl
yg teken L1+dpaddown+r3 tidak keluar menunya

dan kalau install nxthema bermasalh terus

mohon dicek dan terima kasih

**Comment by sthetix** [comment]
Saya cek sih jalan. Tapi tar saya cek ulang deh.
