### ISSUE TITLE
AIO Switch Updater Integration

### ISSUE THREAD

**Issue by pokeimon** [sthetix/HATS#20]
I would like to add the HATS pack to custom_packs.json for AIO Switch Updater .

On your releases, besides including the zip file "HATS-1.5.2-2.zip" can you also add "HATS.zip" with the same content?

This way in the latest HATS pack can be added to the json file like:
```
{
    "ams": {
        "HATS": "https://github.com/sthetix/HATS/releases/latest/download/HATS.zip"
    },
}
```

**Comment by sthetix** [comment]
another person requested to have several variants because they don't want
to lose the update files.. what should I do? 😂

**Comment by pokeimon** [comment]
I think there is a misunderstanding or I am missing something as well 😂. 

Keep the several releases for archival purposes.
But when creating a new release in the future, just upload two files instead of one when it asks "Attach binaries by dropping them here or selecting them. "

One "HATS-x-x-xzip" where x is your release version and another just called "HATS.zip"

Does that make sense, or did I miss something?

**Comment by sthetix** [comment]
okay bro.

**Comment by sthetix** [comment]
You can use the AIO updater to update the pack.
here the link to the config file https://github.com/sthetix/HATS/releases/download/Latest/config.zip
and here's the permanent link to the pack https://github.com/sthetix/HATS/releases/download/Latest/HATS.zip
