### ISSUE TITLE
tesla menu error

### ISSUE THREAD

**Issue by pablomuri** [sthetix/HATS#21]
Hello I am having this error just after a fresh install. I have to remove the tesla content folder to make it run.

Thanks for the pack!

<img width="1105" alt="Captura de pantalla 2023-04-26 a las 18 46 28" src="https://user-images.githubusercontent.com/13034720/234646017-71ba8421-33e4-4a51-8130-2223892feaa6.png">

**Comment by sthetix** [comment]
I assume you are using a Mac.

So please do the Fix Archive Bit procedure

On Hekate, select Tools. And on that screen, select Arch Bit on the bottom,
then on the next page, select Fix Archive Bit

Hope you can fix the issue

**Comment by pablomuri** [comment]
Yes, I was using Mac and it fixed the problem. Thanks a lot!

BR/Pablo
