### ISSUE TITLE
Tesla/Status-Monitor overlay crashing

### ISSUE THREAD

**Issue by kojimon23** [sthetix/HATS#22]
Selecting Status-Monitor from Tesla immediately crashing the system - it used to work couple updates prior. Am I doing something wrong or should I have delete some files?

Much thanks!

**Comment by sthetix** [comment]
I have no issue like that, please try to re-extract the new hats pack.

**Comment by kojimon23** [comment]
Ok thanks. I appreciate your HATS pack very much!

Btw, do you have instructions for updating via AIO updater? Or is cut and
paste with the sdcard preferred?

Much thanks!

ᐧ

**Comment by sthetix** [comment]
You can use the AIO updater (the config file is included inside the newest
hats pack), and later you can update using that app online.
but copy paste to the sd card is fine too
