### ISSUE TITLE
Unable to use most features. 

### ISSUE THREAD

**Issue by BlackPhoenix002** [sthetix/HATS#23]
When trying to launch the CFW (SYSMMC) gives error of unknown pkg1 version ect failed to launch HOS. It does launch into CFW(EMUMMC) although I'm unable to launch any games or download any games. Basically just can get into it but nothing past that. When trying to reboot to OFW screen goes black and does nothing. I need to take out the SD card and hold power for it to get back into Hekate. I'm using a 256gb gigastone if that matters. Went the RP2040 picofly route with I would assume is a V2 switch.side note it gives a message that that eMMC is in slower mode and failed 2 read/writes if that helps.

**Comment by sthetix** [comment]
it has nothing to do with pack.
your modchip has either a compability issue with the sdcard or your sdcard
connector has an issue.

**Comment by BlackPhoenix002** [comment]
Alright thanks Il look into a different one or see if my SD card connector is partially unplugged or in properly plugged in. Is there a specific type of SD that works?brand?

**Comment by sthetix** [comment]
it depends on the modchip itself.. like the instinct-nx has incompatibility
issue with some Samsung evo cards, and the hwfly with the sandisk ultra
cards.

**Comment by BlackPhoenix002** [comment]
Are you aware of any compatibility issues with the RP2040-Zero and the PICOFLY firmware? https://gbatemp.net/threads/picofly-aio-thread.628951/
This is the guide I used if this is any help to what im talking about

**Comment by sthetix** [comment]
you better ask them, because I don't use Pico and I wont use it until it is
settled perfectly.. it's just an "alpha" chip, not ready or not reliable
for commercial purpose.

**Comment by BlackPhoenix002** [comment]
I asked them so i guess i just need to wait for a response, thanks for the quick responses
