### ISSUE TITLE
[REQUEST] Add picofly toolbox payload to Hats

### ISSUE THREAD

**Issue by martimparente** [sthetix/HATS#25]
Hi, 

Can you add the picofly toolbox payload to your pack?
It's very useful for people that use your pack but have the picofly mod and need to update the rp2040 firmware ;)

Thank you 😊

**Comment by sthetix** [comment]
sorry i dont know anything about the picofly toolbox payload, because I
don't use it. maybe you can add it yourself?

**Comment by martimparente** [comment]
I usually do ofc, its just that since a lot of people use your package and also use other mods it would be helpful to skip that part

**Comment by sthetix** [comment]
any link for it?

**Comment by martimparente** [comment]
Yeah 
The official firmware and toolbox are here

https://github.com/Ansem-SoD/Picofly/tree/main/Firmwares

**Comment by sthetix** [comment]
Added the picofly toolbox,.
