### ISSUE TITLE
partitioning the sd card makes all files deleted

### ISSUE THREAD

**Issue by carbon248** [sthetix/HATS#27]
partitioning the sd card makes all files deleted. so you need to  reinsert the card in to the pc to copy the files once again in order to boot to any cfw

**Comment by sthetix** [comment]
of course it is. Hekate made it like that, not me.

**Comment by carbon248** [comment]
So is it ok? no need to worry?

**Comment by sthetix** [comment]
Yes, it's fine. but you better make the sdcard backup before partitioning
it to avoid losing the data.
