### ISSUE TITLE
Ban

### ISSUE THREAD

**Issue by KoreanPizzaGuy** [sthetix/HATS#28]
I got ban with serial number blanked

**Comment by sthetix** [comment]
banned has nothing to do with the pack. it depends on the console usage and
user behavior

**Comment by KoreanPizzaGuy** [comment]
One time I used official firmware and I played game that I own and second day I get ban... Even I used all your tutorials to how to use it.

**Comment by KoreanPizzaGuy** [comment]
Never use sysmmc only emummc with wifi and never use nintendo servers... even block servers with dns block

**Comment by sthetix** [comment]
That is 100% impossible. You won't get the ban if you play legit games on
the sysmmc / OFW.
Unless you have installed something like Tinfoil or illegal games on the
sysmmc at least once, and you just deleted it and didn't do the systemwipe.
Or you used cheats on the sysmmc like for Splatoon.

**Comment by KoreanPizzaGuy** [comment]
No I didn't but I really don't care because I don't even play online games on switch but it was really weird to discovered I was banned event I wasn't doing anything wrong

**Comment by MAG-20** [comment]
Did you setup Atmosphere DNS redirection ? Atmosphere/hosts/emummc.txt 

Sometimes people don't set it up.

**Comment by KoreanPizzaGuy** [comment]
Yes I did but maybe I forgot it one time when I was only using ftp server. I guess it would be it

**Comment by KoreanPizzaGuy** [comment]
But it still weird to get ban with blank serial number

**Comment by MAG-20** [comment]
You'd never know for sure if somthing is going to get you banned or not, people do the same thing, one of them going to get banned and the other will not. It is likely Nintendo API choosing a ban depending on how many flags are trigger or somthing.

**Comment by sthetix** [comment]
No bro. The only way you can get the ban is ever install non-legit
games/apps.
You can check it on the GBATemp forum.
When you play safe - run or load legit games only , it should be fine.

**Comment by KoreanPizzaGuy** [comment]
That's why I think it's weird, I played just dance 2023 on official firmware (I bought that game?)

**Comment by sthetix** [comment]
You must be aware that if you ever ONCE, installed Tinfoil or used
non-legit games on the OFW/ Sysmmc, your console will get the ban. Unless
you systemwipe it first before reconnecting the console to the internet.

**Comment by KoreanPizzaGuy** [comment]
I was playing non-legit games on emummc (serial number: XAW00000000000) and my legit games on OFW

**Comment by sthetix** [comment]
The thing is maybe you forgot to play non legit games on the sysmmc, then
you deleted it without doing the systemwipe and the other time you
connected your console to the OFW, you got the ban.

**Comment by KoreanPizzaGuy** [comment]
Never played on sysmmc

**Comment by sthetix** [comment]
Then i cannot help you further about the issue. I will close this issue.
