### ISSUE TITLE
Instructions after install picofly

### ISSUE THREAD

**Issue by shangis12** [sthetix/HATS#29]
Hello
I just installed successfully picofly on board(v2)
And what i need to do next? When i turn on its says no sd card inserted. 
Where can i get instructions to install essentials to download games etc?

**Comment by sthetix** [comment]
sorry i dont use and never use Pico. maybe you can try my pack,
https://github.com/sthetix/HATS/releases

**Comment by shangis12** [comment]
![second-picofly-installation-on-a-oled-model-v0-4k8ufu4t4awa1](https://github.com/sthetix/HATS/assets/130426833/74bbd4da-5df6-4821-b5e7-a8452ed31b67)

I ment what or how i install after that?
How i install HATS?

**Comment by sthetix** [comment]
https://youtu.be/up_sjzKHFeU?si=YTqpaVCg1hl_LI04

You can try doing that. BUT if the console still showing that screen, you
better ask the GBATemp forum to help you with the matter.

**Comment by shangis12** [comment]
Ok succeed with your hats pack but what to do now? How i install/download games? I entered to the emmumc but there nothing related to hats

**Comment by sthetix** [comment]
You need to get your games by yourself and install them using the DBI with
the MTP Responder method https://youtu.be/SEvtKeoIqS8?si=Y_VUdeGXl8UJ61JC
