### ISSUE TITLE
Upgrade sysnand firmware and find that the serial number is wiped and cause Error 2123-0011

### ISSUE THREAD

**Issue by pfjasonwu** [sthetix/HATS#30]
Hello, thanks for the work. However, I have a problem. When I followed your instruction and upgrade my sysnand. I found that in my sysnand, the serial number have been whiped (turn in to XAW0000). Thus when I tried to link to nintendo in sysnand, it gives me a Error 2123-0011. 
I have entered the OFW and I am able to go online so I am not banned.
Is there any way I can fix this so I can get to nintendo online in sysnand? (I have backed up my keys using lockpick) Thanks.

**Comment by sthetix** [comment]
The console serial number is not wiped. It is the exosphere.ini in charge
to hide the console serial number
You need to get  to the OFW mode to link your Nintendo account
Please read the HATS description thoroughly

**Comment by pfjasonwu** [comment]
I will look the HATS description up. Sorry to bother you. Thanks a lot.

**Comment by pfjasonwu** [comment]
Yest, it works. Really appreciate for the help.

**Comment by sthetix** [comment]
Glad it worked.
