### ISSUE TITLE
Error 2002-1002

### ISSUE THREAD

**Issue by shangis12** [sthetix/HATS#31]
Hello
Im facing a problem 
I try to open game with game card or any other eshop game and i got error 2002-1002 even on YouTube 
I tried to power off, restart and still the same.
Only jailbreak stuff work(HB,tinfoil etc)
What is the solution for this?

**Comment by sthetix** [comment]
https://gbatemp.net/threads/error-code-2002-1002-cant-start-this-game.564813/

maybe the profile is corrupted etc

**Comment by shangis12** [comment]
I tried to open game with different profiles and still dosent work even eshop original games same error

**Comment by sthetix** [comment]
try to do the systemwipe and re extract my pack.. be aware that all the
save and game will be wiped.

**Comment by shangis12** [comment]
System wipe via ofw?
And can i backup save game and put it back after wipe?
And re extract your pack to sd card?  start all over again like in your video if fresh start?

**Comment by sthetix** [comment]
systemwipe via hekate. there is a guide on my channel. you can extract the
save data using jksv, there is a guide on my channel too

**Comment by shangis12** [comment]
I succeeded by delete save data of the game but now i have to start a new game and all my progress has been lost.
Where and how i can get save games to put my NS?

**Comment by sthetix** [comment]
if the save data is corrupted then u need to play it again from the
beginning. and I don't know where to get the save data from

**Comment by shangis12** [comment]
In ofw i have the progress i ahd before but in cfw o have to play new save game.
How can i transfer from ofw to cfw?
When i enter jksv i dont see the save games that are from ofw

**Comment by sthetix** [comment]
https://youtu.be/HoyvuH2GU0Q?si=OTRbUjaiqOrbs-c_
