### ISSUE TITLE
Hats 1.6.2

### ISSUE THREAD

**Issue by Aliblu89** [sthetix/HATS#40]
Hello, 
thanks again for the continuous great work!

This is currently whats in my SD card that is working correctly. Can you tell me what to keep and what to remove please for me to upgrade to the 1.6.2 release that you just put out?

![hats](https://github.com/sthetix/HATS/assets/148637777/19a32c37-484e-4afa-a97d-15f2126b6657)

**Comment by sthetix** [comment]
Just delete the Atmosphere and the Bootloader folder and re-extract the new
pack.

**Comment by Aliblu89** [comment]
Perfect that worked!!!!!!!!!!! Thank you brother.
