### ISSUE TITLE
Error Fusee.

### ISSUE THREAD

**Issue by central1986** [sthetix/HATS#9]
Hello,

When I put hats on the sd card I get the following message: A fatal error occurred when running fusee. Incorrect fusee version! (program=0xb6b6ac70 mtc=0xb46dcf71) Please how do I fix this, I have little technical knowledge.

Thanks for your good work, I always use your guides, you are the best.

**Comment by sthetix** [comment]
On hekate, press launch then sysmmc / emummc.

I didn't put the fusee.bin inside the pack.

Please try that first

**Comment by central1986** [comment]
It worked! Thank you!
